### ISSUE TITLE
Middle image is blurry

### ISSUE THREAD

**Issue by ninjapanzer** [cornerstone-rm/lten_landing_page#2]
<img width="1653" alt="screen shot 2017-04-24 at 12 17 01 pm" src="https://cloud.githubusercontent.com/assets/159591/25347186/053c2d1a-28e8-11e7-9732-a01aad9a4b63.png">

**Comment by aloya** [comment]
This original graphic is quite large and clear. it only pixels it when adding in in mobi another sad thing

**Comment by ninjapanzer** [comment]
There is an option on the page in mobirise to resize images. Probably just turn that off
