### ISSUE TITLE
Title Font Overflows

### ISSUE THREAD

**Issue by ninjapanzer** [cornerstone-rm/lten_landing_page#3]
<img width="489" alt="screen shot 2017-04-24 at 12 17 57 pm" src="https://cloud.githubusercontent.com/assets/159591/25347209/1a1b3dac-28e8-11e7-86c6-d67a197c618f.png">

Probably missing a font. Adapt with fig

**Comment by garyanewsome** [comment]
http://leadwithcornerstone.com/lten_landing_page/ when looking at the page in real life this works

<img width="342" alt="screen shot 2017-04-24 at 1 11 34 pm" src="https://cloud.githubusercontent.com/assets/13909325/25349396/ba0ccd24-28ef-11e7-932c-bc29a16ff690.png">

Alex and I noticed this right away, it looks like poop in mobirise but as soon as you preview it in a browser its good

**Comment by ninjapanzer** [comment]
My screenshot is from the browser not mobirise

**Comment by garyanewsome** [comment]
grrrr
